### ISSUE TITLE
Error parsing NaN value

### ISSUE THREAD

**Issue by delgelato** [Gazuntype/GraphQL-Unity-Client#10]
Hi. I'm new to GraphQl. I want to do some fetch from https://axieinfinity.com/graphql-server/graphql, but whatever variation of the url i do (without https://, without the last graphql, with a / at the end, etc), i always get this:

JsonReaderException: Error parsing NaN value. Path '', line 1, position 1.

It must be something simple but i really wanna try this out...

Cheers

edit:
I'm now getting the same as the last post in here https://github.com/Gazuntype/graphQL-client-unity/issues/6
The ScriptableObject UI is not showing, and the console spams NullRef in Assets/graphQl-client/Scripts/Core/GraphApi.cs:153
Restarting Unity doesn't help, the spam continues

**Comment by gazuntype** [comment]
hi @delgelato ,

you can't fetch data from https://axieinfinity.com/graphql-server/graphql because it is not a valid API. i do not believe AxieInfinity has an open graphQL endpoint, and if they do, this isn't the endpoint.

an easy way to know if an endpoint is a valid graphQL endpoint is by putting it in your browser and checking if a graphiQL gui pops up.
